### ISSUE TITLE
Process cpu usage 

### ISSUE THREAD

**Issue by vliux** [NetEase/Emmagee#41]
I took a look into the implementation of getting a standalone process cpu usage. But seems the solution is wrong, as the units of /proc/stat and /proc/pid/stat are different. The former is in 1/100 second, while the latter is in CPU clocks. So a unit transition is required.

**Comment by andrewleo** [comment]
First of all , thanks for your attention to Emmagee!
As you have memtioned, a transition is required because of the different unit, however I thought they have the same unit called jiffies.
Can you  provide some references so that we can find out the correct solution? And I will take some time to verify current solution as well.
If you have any idea, please add a commet here, thanks!
